In [2]:
import pandas as pd

In [3]:

df = pd.read_csv('../staging/staging_data.csv')
df = df.sort_values(by="lpep_pickup_datetime", ascending=True)

df.head(25)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
261311,2,2009-01-01 00:05:59,2009-01-01 10:52:23,N,1,193,193,1,0.00,0.0,0.0,0.0,0.00,0.00,NaN,0.0,0.00,1,1,NaN
249115,2,2009-01-01 00:06:03,2009-01-01 00:06:03,N,1,264,193,1,0.00,0.0,0.0,0.0,0.00,0.00,NaN,0.0,0.00,2,1,NaN
135441,2,2009-01-01 00:07:44,2009-01-01 00:17:01,N,1,97,181,1,1.88,8.5,0.0,0.5,0.00,0.00,NaN,0.3,9.30,2,1,NaN
229802,2,2009-01-01 00:08:14,2009-01-01 00:48:13,N,1,53,92,2,2.95,24.5,0.0,0.5,0.00,0.00,NaN,0.3,25.30,2,1,NaN
468399,2,2009-01-01 00:18:07,2009-01-01 00:45:15,N,1,166,68,1,5.95,22.5,0.0,0.5,0.00,0.00,NaN,0.3,23.30,2,1,0.0
135442,2,2009-01-01 00:37:11,2009-01-01 00:49:20,N,1,25,148,1,2.65,11.5,0.0,0.5,0.00,0.00,NaN,0.3,12.30,2,1,NaN
116131,2,2009-01-01 00:40:26,2009-01-01 00:46:05,N,1,33,33,1,0.47,5.5,0.0,0.5,0.00,0.00,NaN,0.3,6.30,2,1,NaN
136409,2,2009-01-01 01:01:30,2009-01-01 01:13:23,N,1,25,49,1,1.61,8.5,0.5,0.5,0.00,0.00,NaN,0.3,9.80,2,1,NaN
116132,2,2009-01-01 01:01:41,2009-01-01 01:25:30,N,1,33,137,1,5.78,20.5,0.0,0.5,0.00,0.00,NaN,0.3,21.30,2,1,NaN
249149,2,2009-01-01 01:17:20,2009-01-01 02:27:07,N,1,92,146,2,11.23,48.0,0.0,0.5,0.00,0.00,NaN,0.3,48.80,2,1,NaN
136410,2,2009-01-01 01:41:56,2009-01-01 01:48:59,N,1,65,49,1,1.69,7.5,0.5,0.5,0.00,0.00,NaN,0.3,8.80,2,1,NaN
228585,2,2009-01-01 01:50:18,2009-01-01 02:34:34,N,1,173,92,2,8.24,33.0,0.0,0.5,0.00,0.00,NaN,0.3,33.80,2,1,NaN
44243,2,2009-01-01 23:49:47,2009-01-02 00:02:08,N,1,7,193,1,0.00,3.0,0.0,0.5,0.00,0.00,NaN,0.3,3.80,2,1,NaN
211042,2,2010-09-23 00:01:14,2010-09-23 14:48:48,N,1,193,7,1,0.00,0.0,0.0,0.0,0.00,0.00,NaN,0.0,0.00,1,1,NaN
67608,2,2010-09-23 01:01:28,2010-09-23 15:17:37,N,1,56,130,5,6.08,20.5,0.0,0.5,3.00,0.00,NaN,0.3,24.30,1,1,NaN
523032,2,2010-09-23 01:01:32,2010-09-23 12:21:08,N,1,215,9,5,6.57,26.5,0.0,0.5,0.00,0.00,NaN,0.3,27.30,2,1,0.0
322087,2,2010-09-23 01:01:59,2010-09-23 20:30:49,N,1,193,146,1,1.02,5.0,0.5,0.5,0.00,0.00,NaN,0.3,6.30,1,1,NaN
396197,2,2010-09-23 01:10:04,2010-09-23 01:12:22,N,1,179,179,1,0.42,3.5,0.5,0.5,0.96,0.00,NaN,0.3,5.76,1,1,NaN
396198,2,2010-09-23 01:17:30,2010-09-23 01:21:09,N,1,7,7,1,0.57,4.5,0.5,0.5,0.00,0.00,NaN,0.3,5.80,2,1,NaN
398691,2,2010-09-23 01:21:47,2010-09-24 01:02:43,N,1,7,193,1,1.40,6.5,0.5,0.5,0.00,0.00,NaN,0.3,7.80,2,1,NaN
395137,2,2010-09-23 01:26:41,2010-09-23 01:31:58,N,1,179,179,1,0.89,5.5,0.5,0.5,0.00,0.00,NaN,0.3,6.80,2,1,NaN
397847,2,2010-09-23 01:27:44,2010-09-23 01:33:31,N,1,7,179,1,0.98,6.0,0.5,0.5,1.46,0.00,NaN,0.3,8.76,1,1,NaN
396199,2,2010-09-23 01:39:05,2010-09-23 02:01:25,N,1,7,230,1,4.38,18.0,0.5,0.5,0.00,0.00,NaN,0.3,19.30,2,1,NaN
397848,2,2010-09-23 01:53:00,2010-09-23 02:01:45,N,1,223,260,1,3.14,11.0,0.5,0.5,0.00,0.00,NaN,0.3,12.30,2,1,NaN
211851,2,2018-12-04 16:01:39,2018-12-05 00:00:00,N,1,193,193,5,0.00,4.5,0.0,0.5,0.00,5.76,NaN,0.3,11.06,2,1,NaN

In [4]:
df.isnull().sum()

VendorID                      0
lpep_pickup_datetime          0
lpep_dropoff_datetime         0
store_and_fwd_flag            0
RatecodeID                    0
PULocationID                  0
DOLocationID                  0
passenger_count               0
trip_distance                 0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
ehail_fee                656118
improvement_surcharge         0
total_amount                  0
payment_type                  0
trip_type                     0
congestion_surcharge     571580
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 656118 entries, 261311 to 605322
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               656118 non-null  int64
 1   lpep_pickup_datetime   656118 non-null  object
 2   lpep_dropoff_datetime  656118 non-null  object
 3   store_and_fwd_flag     656118 non-null  object
 4   RatecodeID             656118 non-null  int64
 5   PULocationID           656118 non-null  int64
 6   DOLocationID           656118 non-null  int64
 7   passenger_count        656118 non-null  int64
 8   trip_distance          656118 non-null  float64
 9   fare_amount            656118 non-null  float64
 10  extra                  656118 non-null  float64
 11  mta_tax                656118 non-null  float64
 12  tip_amount             656118 non-null  float64
 13  tolls_amount           656118 non-null  float64
 14  ehail_fee              0 non-null       float64
 15  improvement_surcharge  656118 non-null  float64
 16  total_amount           656118 non-null  float64
 17  payment_type           656118 non-null  int64
 18  trip_type              656118 non-null  int64
 19  congestion_surcharge   84538 non-null   float64
dtypes: float64(10), int64(7), object(3)
memory usage: 105.1+ MB

In [6]:
payment_master = pd.read_csv('../data/payment_type.csv')
df_new = df.merge(payment_master, on="payment_type", how="left", validate="many_to_one")
df_new.rename(columns={"description": "payment_description"}, inplace=True)  # Rename new column
cols = df_new.columns.tolist()
payment_type_index = cols.index('payment_type')
payment_description_index = cols.index('payment_description')
payment_description_col = cols.pop(payment_description_index)
cols.insert(payment_type_index, payment_description_col)
df_new = df_new[cols]
df_new.drop(columns=['payment_type'], inplace=True)
df_new.rename(columns={"payment_description": 'payment_type'}, inplace=True)
df_new.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2009-01-01 00:05:59,2009-01-01 10:52:23,N,1,193,193,1,0.00,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,Credit Card,1,NaN
1,2,2009-01-01 00:06:03,2009-01-01 00:06:03,N,1,264,193,1,0.00,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,Cash,1,NaN
2,2,2009-01-01 00:07:44,2009-01-01 00:17:01,N,1,97,181,1,1.88,8.5,0.0,0.5,0.0,0.0,NaN,0.3,9.3,Cash,1,NaN
3,2,2009-01-01 00:08:14,2009-01-01 00:48:13,N,1,53,92,2,2.95,24.5,0.0,0.5,0.0,0.0,NaN,0.3,25.3,Cash,1,NaN
4,2,2009-01-01 00:18:07,2009-01-01 00:45:15,N,1,166,68,1,5.95,22.5,0.0,0.5,0.0,0.0,NaN,0.3,23.3,Cash,1,0.0

In [7]:
df_new["lpep_pickup_datetime"] = pd.to_datetime(df_new["lpep_pickup_datetime"])
df_new["lpep_dropoff_datetime"] = pd.to_datetime(df_new["lpep_dropoff_datetime"])
df_new["trip_duration"] = (df_new["lpep_dropoff_datetime"] - df_new["lpep_pickup_datetime"])

df_new.info()

df_new.head(20)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 656118 entries, 0 to 656117
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               656118 non-null  int64
 1   lpep_pickup_datetime   656118 non-null  datetime64[ns]
 2   lpep_dropoff_datetime  656118 non-null  datetime64[ns]
 3   store_and_fwd_flag     656118 non-null  object
 4   RatecodeID             656118 non-null  int64
 5   PULocationID           656118 non-null  int64
 6   DOLocationID           656118 non-null  int64
 7   passenger_count        656118 non-null  int64
 8   trip_distance          656118 non-null  float64
 9   fare_amount            656118 non-null  float64
 10  extra                  656118 non-null  float64
 11  mta_tax                656118 non-null  float64
 12  tip_amount             656118 non-null  float64
 13  tolls_amount           656118 non-null  float64
 14  ehail_fee              0 non-null       float64
 15  improvement_surcharge  656118 non-null  float64
 16  total_amount           656118 non-null  float64
 17  payment_type           656118 non-null  object
 18  trip_type              656118 non-null  int64
 19  congestion_surcharge   84538 non-null   float64
 20  trip_duration          656118 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), float64(10), int64(6), object(2), timedelta64[ns](1)
memory usage: 110.1+ MB

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,trip_duration
0,2,2009-01-01 00:05:59,2009-01-01 10:52:23,N,1,193,193,1,0.00,0.0,...,0.0,0.00,0.0,NaN,0.0,0.00,Credit Card,1,NaN,0 days 10:46:24
1,2,2009-01-01 00:06:03,2009-01-01 00:06:03,N,1,264,193,1,0.00,0.0,...,0.0,0.00,0.0,NaN,0.0,0.00,Cash,1,NaN,0 days 00:00:00
2,2,2009-01-01 00:07:44,2009-01-01 00:17:01,N,1,97,181,1,1.88,8.5,...,0.5,0.00,0.0,NaN,0.3,9.30,Cash,1,NaN,0 days 00:09:17
3,2,2009-01-01 00:08:14,2009-01-01 00:48:13,N,1,53,92,2,2.95,24.5,...,0.5,0.00,0.0,NaN,0.3,25.30,Cash,1,NaN,0 days 00:39:59
4,2,2009-01-01 00:18:07,2009-01-01 00:45:15,N,1,166,68,1,5.95,22.5,...,0.5,0.00,0.0,NaN,0.3,23.30,Cash,1,0.0,0 days 00:27:08
5,2,2009-01-01 00:37:11,2009-01-01 00:49:20,N,1,25,148,1,2.65,11.5,...,0.5,0.00,0.0,NaN,0.3,12.30,Cash,1,NaN,0 days 00:12:09
6,2,2009-01-01 00:40:26,2009-01-01 00:46:05,N,1,33,33,1,0.47,5.5,...,0.5,0.00,0.0,NaN,0.3,6.30,Cash,1,NaN,0 days 00:05:39
7,2,2009-01-01 01:01:30,2009-01-01 01:13:23,N,1,25,49,1,1.61,8.5,...,0.5,0.00,0.0,NaN,0.3,9.80,Cash,1,NaN,0 days 00:11:53
8,2,2009-01-01 01:01:41,2009-01-01 01:25:30,N,1,33,137,1,5.78,20.5,...,0.5,0.00,0.0,NaN,0.3,21.30,Cash,1,NaN,0 days 00:23:49
9,2,2009-01-01 01:17:20,2009-01-01 02:27:07,N,1,92,146,2,11.23,48.0,...,0.5,0.00,0.0,NaN,0.3,48.80,Cash,1,NaN,0 days 01:09:47
10,2,2009-01-01 01:41:56,2009-01-01 01:48:59,N,1,65,49,1,1.69,7.5,...,0.5,0.00,0.0,NaN,0.3,8.80,Cash,1,NaN,0 days 00:07:03
11,2,2009-01-01 01:50:18,2009-01-01 02:34:34,N,1,173,92,2,8.24,33.0,...,0.5,0.00,0.0,NaN,0.3,33.80,Cash,1,NaN,0 days 00:44:16
12,2,2009-01-01 23:49:47,2009-01-02 00:02:08,N,1,7,193,1,0.00,3.0,...,0.5,0.00,0.0,NaN,0.3,3.80,Cash,1,NaN,0 days 00:12:21
13,2,2010-09-23 00:01:14,2010-09-23 14:48:48,N,1,193,7,1,0.00,0.0,...,0.0,0.00,0.0,NaN,0.0,0.00,Credit Card,1,NaN,0 days 14:47:34
14,2,2010-09-23 01:01:28,2010-09-23 15:17:37,N,1,56,130,5,6.08,20.5,...,0.5,3.00,0.0,NaN,0.3,24.30,Credit Card,1,NaN,0 days 14:16:09
15,2,2010-09-23 01:01:32,2010-09-23 12:21:08,N,1,215,9,5,6.57,26.5,...,0.5,0.00,0.0,NaN,0.3,27.30,Cash,1,0.0,0 days 11:19:36
16,2,2010-09-23 01:01:59,2010-09-23 20:30:49,N,1,193,146,1,1.02,5.0,...,0.5,0.00,0.0,NaN,0.3,6.30,Credit Card,1,NaN,0 days 19:28:50
17,2,2010-09-23 01:10:04,2010-09-23 01:12:22,N,1,179,179,1,0.42,3.5,...,0.5,0.96,0.0,NaN,0.3,5.76,Credit Card,1,NaN,0 days 00:02:18
18,2,2010-09-23 01:17:30,2010-09-23 01:21:09,N,1,7,7,1,0.57,4.5,...,0.5,0.00,0.0,NaN,0.3,5.80,Cash,1,NaN,0 days 00:03:39
19,2,2010-09-23 01:21:47,2010-09-24 01:02:43,N,1,7,193,1,1.40,6.5,...,0.5,0.00,0.0,NaN,0.3,7.80,Cash,1,NaN,0 days 23:40:56

In [8]:
df_new.columns = df_new.columns.str.replace(r'(?<=[a-z0-9])([A-Z])', r'_\1', regex=True).str.replace(r'(?<!^)(?=[A-Z][a-z])', '_', regex=True).str.lower()
df_new.columns
df_new.head(5)

,vendor_id,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,ratecode_id,pu_location_id,do_location_id,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,trip_duration
0,2,2009-01-01 00:05:59,2009-01-01 10:52:23,N,1,193,193,1,0.00,0.0,...,0.0,0.0,0.0,NaN,0.0,0.0,Credit Card,1,NaN,0 days 10:46:24
1,2,2009-01-01 00:06:03,2009-01-01 00:06:03,N,1,264,193,1,0.00,0.0,...,0.0,0.0,0.0,NaN,0.0,0.0,Cash,1,NaN,0 days 00:00:00
2,2,2009-01-01 00:07:44,2009-01-01 00:17:01,N,1,97,181,1,1.88,8.5,...,0.5,0.0,0.0,NaN,0.3,9.3,Cash,1,NaN,0 days 00:09:17
3,2,2009-01-01 00:08:14,2009-01-01 00:48:13,N,1,53,92,2,2.95,24.5,...,0.5,0.0,0.0,NaN,0.3,25.3,Cash,1,NaN,0 days 00:39:59
4,2,2009-01-01 00:18:07,2009-01-01 00:45:15,N,1,166,68,1,5.95,22.5,...,0.5,0.0,0.0,NaN,0.3,23.3,Cash,1,0.0,0 days 00:27:08

In [9]:
df_new['trip_distance'] = (df_new['trip_distance'] * 1.60934).round(2)
df_new.head(5)

,vendor_id,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,ratecode_id,pu_location_id,do_location_id,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,trip_duration
0,2,2009-01-01 00:05:59,2009-01-01 10:52:23,N,1,193,193,1,0.00,0.0,...,0.0,0.0,0.0,NaN,0.0,0.0,Credit Card,1,NaN,0 days 10:46:24
1,2,2009-01-01 00:06:03,2009-01-01 00:06:03,N,1,264,193,1,0.00,0.0,...,0.0,0.0,0.0,NaN,0.0,0.0,Cash,1,NaN,0 days 00:00:00
2,2,2009-01-01 00:07:44,2009-01-01 00:17:01,N,1,97,181,1,3.03,8.5,...,0.5,0.0,0.0,NaN,0.3,9.3,Cash,1,NaN,0 days 00:09:17
3,2,2009-01-01 00:08:14,2009-01-01 00:48:13,N,1,53,92,2,4.75,24.5,...,0.5,0.0,0.0,NaN,0.3,25.3,Cash,1,NaN,0 days 00:39:59
4,2,2009-01-01 00:18:07,2009-01-01 00:45:15,N,1,166,68,1,9.58,22.5,...,0.5,0.0,0.0,NaN,0.3,23.3,Cash,1,0.0,0 days 00:27:08

In [11]:
df_new.info()
df_new['pu_location_id'].value_counts()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 656118 entries, 0 to 656117
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   vendor_id              656118 non-null  int64
 1   lpep_pickup_datetime   656118 non-null  datetime64[ns]
 2   lpep_dropoff_datetime  656118 non-null  datetime64[ns]
 3   store_and_fwd_flag     656118 non-null  object
 4   ratecode_id            656118 non-null  int64
 5   pu_location_id         656118 non-null  int64
 6   do_location_id         656118 non-null  int64
 7   passenger_count        656118 non-null  int64
 8   trip_distance          656118 non-null  float64
 9   fare_amount            656118 non-null  float64
 10  extra                  656118 non-null  float64
 11  mta_tax                656118 non-null  float64
 12  tip_amount             656118 non-null  float64
 13  tolls_amount           656118 non-null  float64
 14  ehail_fee              0 non-null       float64
 15  improvement_surcharge  656118 non-null  float64
 16  total_amount           656118 non-null  float64
 17  payment_type           656118 non-null  object
 18  trip_type              656118 non-null  int64
 19  congestion_surcharge   84538 non-null   float64
 20  trip_duration          656118 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), float64(10), int64(6), object(2), timedelta64[ns](1)
memory usage: 110.1+ MB

74     44568
75     41685
41     34845
7      26971
82     25721
       ...
176        2
151        1
27         1
144        1
224        1
Name: pu_location_id, Length: 256, dtype: int64